modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
displayTest="IGNORE_ALL_VERSION"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Experimental NVIDIA DLSS and DLAA integration for Minecraft 26.2's native Vulkan backend.
'''
clientSideOnly=true

[[mixins]]
config="nvidia_dlss.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
